import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import type { CategoryFieldSchema } from './schema';
import { validateFieldValues, type FieldIssue, type ValidationContext } from './validation';

/**
 * Parity with the server: fixtures/validation-cases.json holds payloads and
 * the issues the API's own validator reported for each (generated by
 * `pnpm --filter @amar-elaka/api fixtures:export`). The client must agree on
 * every one.
 */

const fixture = <T>(name: string): T =>
  JSON.parse(readFileSync(new URL(`../fixtures/${name}`, import.meta.url), 'utf8')) as T;

const schemas: Record<string, CategoryFieldSchema> = {
  'to-let': fixture<{ fieldSchema: CategoryFieldSchema }>('to-let.json').fieldSchema,
  'rent-a-car': fixture<{ fieldSchema: CategoryFieldSchema }>('rent-a-car.json').fieldSchema,
};
const { context, cases } = fixture<{
  context: ValidationContext;
  cases: { category: string; name: string; values: unknown; issues: FieldIssue[] }[];
}>('validation-cases.json');

const sorted = (issues: FieldIssue[]) =>
  [...issues].sort((a, b) =>
    a.field === b.field ? a.code.localeCompare(b.code) : a.field.localeCompare(b.field),
  );

describe('client validation mirrors the server', () => {
  it('has server verdicts to compare against', () => {
    expect(cases.length).toBeGreaterThan(10);
  });

  it.each(cases.map((c) => [`${c.category}: ${c.name}`, c] as const))('%s', (_, c) => {
    expect(sorted(validateFieldValues(schemas[c.category]!.jsonSchema, c.values, context))).toEqual(
      c.issues,
    );
  });
});
