import {
  JOB_CLEAN_ORPHAN_MEDIA,
  JOB_CLEAN_STALE_DRAFTS,
  JOB_BUILD_OFFLINE_MAPS,
  JOB_DETECT_DUPLICATES,
  JOB_EXPIRE_POSTS,
  JOB_FLUSH_POST_VIEWS,
  JOB_MATCH_SAVED_SEARCHES,
  JOB_PAUSE_IDLE_SAVED_SEARCHES,
  JOB_PURGE_DELETED_MEDIA,
  JOB_PURGE_GEO_PROVIDER_CALLS,
  JOB_REFRESH_UNMET_DEMAND,
  JOB_RELAY_NOTIFICATION_OUTBOX,
  JOB_REMIND_EXPIRING_POSTS,
  JOB_ROLLUP_ANALYTICS,
  JOB_SEND_SAVED_SEARCH_DIGESTS,
  QUEUE_GEO,
  QUEUE_MEDIA,
  QUEUE_MAP,
  QUEUE_NOTIFICATIONS,
  QUEUE_PLACES,
  QUEUE_POSTS,
  QUEUE_SAVED_SEARCHES,
} from '../queue/queue.types';

/**
 * The scheduled lifecycle jobs (ADR 031) and the queue each runs on. Codes
 * are the BullMQ job names, the job-scheduler keys and the `scheduled_jobs`
 * lookup codes (0028) — one name everywhere.
 */
export const SCHEDULED_JOBS = {
  [JOB_EXPIRE_POSTS]: { queue: QUEUE_POSTS },
  [JOB_REMIND_EXPIRING_POSTS]: { queue: QUEUE_POSTS },
  [JOB_CLEAN_STALE_DRAFTS]: { queue: QUEUE_POSTS },
  [JOB_FLUSH_POST_VIEWS]: { queue: QUEUE_POSTS },
  [JOB_ROLLUP_ANALYTICS]: { queue: QUEUE_POSTS },
  [JOB_CLEAN_ORPHAN_MEDIA]: { queue: QUEUE_MEDIA },
  [JOB_PURGE_DELETED_MEDIA]: { queue: QUEUE_MEDIA },
  [JOB_MATCH_SAVED_SEARCHES]: { queue: QUEUE_SAVED_SEARCHES },
  [JOB_PAUSE_IDLE_SAVED_SEARCHES]: { queue: QUEUE_SAVED_SEARCHES },
  [JOB_REFRESH_UNMET_DEMAND]: { queue: QUEUE_SAVED_SEARCHES },
  [JOB_PURGE_GEO_PROVIDER_CALLS]: { queue: QUEUE_GEO },
  [JOB_DETECT_DUPLICATES]: { queue: QUEUE_PLACES },
  [JOB_BUILD_OFFLINE_MAPS]: { queue: QUEUE_MAP },
  [JOB_RELAY_NOTIFICATION_OUTBOX]: { queue: QUEUE_NOTIFICATIONS },
  [JOB_SEND_SAVED_SEARCH_DIGESTS]: { queue: QUEUE_SAVED_SEARCHES },
} as const;

export type ScheduledJobCode = keyof typeof SCHEDULED_JOBS;

export const SCHEDULED_JOB_CODES = Object.keys(SCHEDULED_JOBS) as [
  ScheduledJobCode,
  ...ScheduledJobCode[],
];

export function isScheduledJobCode(name: string): name is ScheduledJobCode {
  return name in SCHEDULED_JOBS;
}
