import 'dart:convert';
import 'dart:io';

import 'package:amar_elaka_app/core/map/map_style.dart';
import 'package:flutter_test/flutter_test.dart';

/// The bundled styles (assets/map, generated by packages/map-style) resolve
/// the same way the web's resolveStyle() does: archive and asset URLs filled
/// in, every name label in the chosen language, road shields untouched.
void main() {
  final labels =
      jsonDecode(File('assets/map/labels.json').readAsStringSync())
          as Map<String, dynamic>;

  Map<String, dynamic> resolve(String theme, String lang) =>
      jsonDecode(
            MapStyles.resolve(
              File('assets/map/$theme.json').readAsStringSync(),
              labels,
              tilesUrl: 'https://tiles.amarelaka.com/tiles/bd-20261005.pmtiles',
              assetsBaseUrl: 'https://tiles.amarelaka.com/tiles/',
              labelLanguage: lang,
            ),
          )
          as Map<String, dynamic>;

  for (final theme in ['light', 'dark']) {
    group('$theme style', () {
      test('reads the versioned archive and self-hosted assets', () {
        final style = resolve(theme, 'bn');
        final json = jsonEncode(style);
        expect(json, isNot(contains(MapStyles.tilesPlaceholder)));
        expect(json, isNot(contains(MapStyles.assetsPlaceholder)));
        expect(
          (style['sources'] as Map)['protomaps'],
          containsPair(
            'url',
            'pmtiles://https://tiles.amarelaka.com/tiles/bd-20261005.pmtiles',
          ),
        );
        expect(
          style['glyphs'],
          'https://tiles.amarelaka.com/tiles/fonts/{fontstack}/{range}.pbf',
        );
        expect(
          style['sprite'],
          'https://tiles.amarelaka.com/tiles/sprites/v4/$theme',
        );
      });

      test('shapes Bengali from the self-hosted Noto Sans Bengali files', () {
        final faces = resolve(theme, 'bn')['font-faces'] as Map;
        expect(
          ((faces['Noto Sans Regular'] as List).single as Map)['url'],
          'https://tiles.amarelaka.com/tiles/fonts/bengali/NotoSansBengali-Regular.ttf',
        );
      });

      for (final lang in ['bn', 'en']) {
        test(
          'writes every name label in $lang, leaving road shields alone',
          () {
            final layers = (resolve(theme, lang)['layers'] as List)
                .cast<Map<String, dynamic>>();
            final named = layers.where(
              (l) =>
                  (l['metadata'] as Map?)?[MapStyles.labelMetadataKey] == true,
            );
            expect(named.length, greaterThanOrEqualTo(10));
            for (final layer in named) {
              expect((layer['layout'] as Map)['text-field'], labels[lang]);
            }
            final shields = layers.singleWhere(
              (l) => l['id'] == 'roads_shields',
            );
            expect((shields['layout'] as Map)['text-field'], [
              'get',
              'shield_text',
            ]);
          },
        );
      }

      test('carries the OpenStreetMap and Protomaps credit', () {
        final source =
            (resolve(theme, 'en')['sources'] as Map)['protomaps'] as Map;
        expect(source['attribution'], contains('OpenStreetMap contributors'));
        expect(source['attribution'], contains('Protomaps'));
      });
    });
  }
}
