import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parseSynonymDictionary, type SynonymLine } from './synonym-dictionary';

/**
 * `pnpm --filter @amar-elaka/api search:synonyms`: docs/specs/search-synonyms.md
 * → search-synonyms.generated.ts. The dictionary lives in docs so anyone can
 * edit it; the API ships the generated module (the Docker image has no docs/).
 * synonym-dictionary.spec.ts fails when the two drift apart.
 */

const REPO_ROOT = join(__dirname, '..', '..', '..', '..', '..');
export const DICTIONARY_PATH = join(REPO_ROOT, 'docs', 'specs', 'search-synonyms.md');
export const GENERATED_PATH = join(__dirname, 'search-synonyms.generated.ts');

export function renderGenerated(lines: readonly SynonymLine[]): string {
  const body = lines
    .map(
      ({ terms, expandsTo }) =>
        `  { terms: ${JSON.stringify(terms)}, expandsTo: ${JSON.stringify(expandsTo)} },`,
    )
    .join('\n');
  return `// GENERATED by \`pnpm --filter @amar-elaka/api search:synonyms\` from
// docs/specs/search-synonyms.md. Do not edit — edit the dictionary.
import type { SynonymLine } from './synonym-dictionary';

export const SYNONYM_LINES: readonly SynonymLine[] = [
${body}
];
`;
}

export function generatedFromDictionary(): string {
  return renderGenerated(parseSynonymDictionary(readFileSync(DICTIONARY_PATH, 'utf8')));
}

if (require.main === module) {
  writeFileSync(GENERATED_PATH, generatedFromDictionary());
  console.log(`wrote ${GENERATED_PATH}`);
}
